### PR TITLE
update to the latest class names

### PR DESCRIPTION
**Pull request by yjbanov**

### CODE REVIEW

**Comment by yjbanov** [comment]
> Nit: you might consider renaming your response variables to result

Done. Also realized I needed to rename some things over on Dart side.

**Comment by mravn-google** [comment]
Yeah, also on the iOS side, I'm afraid. FlutterResultReceiver -> FlutterResult

**Comment by yjbanov** [comment]
> also on the iOS side

Now that my forced laptop upgrade is finished, I can fix the iOS side too

**Comment by yjbanov** [comment]
Done. Merging.

**Comment by yjbanov** [comment]
Thanks for the review!

**Pull request merged**
